name: PHPStan

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_TAG: php83-fpm-magento2.4.8
          - IMAGE_TAG: latest

    name: Magento ${{ matrix.IMAGE_TAG }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Magento container
        run: docker run --detach --name magento ghcr.io/controlaltdelete-nl/magento2-in-a-box/magento-project-community-edition:${{ matrix.IMAGE_TAG }}

      - name: Install AI base module
        run: |
          docker exec magento ./retry "composer require --no-update mage-os/module-ai-base:'^1.0'"
          docker exec magento ./retry "composer require --no-update symfony/ai-lm-studio-platform:'*'"

      - name: Upload module into container
        run: |
          sed -i '/version/d' ./composer.json
          docker cp $(pwd) magento:/data/extensions/
          docker exec magento ./install-composer-package mago-assistant/magento2-mago:@dev

      - name: Activate extension
        run: |
          docker exec magento ./retry "php bin/magento module:enable MageOS_AiBase MagoAssistant_Mago && php bin/magento setup:di:compile && php bin/magento setup:upgrade --keep-generated"

      - name: Run PHPStan
        run: docker exec magento /bin/bash -c "./vendor/bin/phpstan analyse --no-progress -c /data/extensions/*/phpstan.neon.dist /data/extensions"
